# Generated by Django 3.2.19 on 2023-06-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20230625_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number_likes',
        ),
    ]
