# Generated by Django 3.2.19 on 2023-06-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
