# Generated by Django 3.2.19 on 2023-07-01 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_doctor_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DoctorApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=1024)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_type', to='network.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_apply_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
