# Generated by Django 3.2.19 on 2023-07-05 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20230701_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='network.doctor'),
        ),
    ]
