# Generated by Django 3.2.19 on 2023-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_message_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_message',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
