# Generated by Django 3.2.20 on 2023-09-13 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_doctor_doctor_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_size', models.CharField(blank=True, max_length=10)),
                ('cloth_item', models.CharField(blank=True, max_length=1024)),
                ('cloth_color', models.CharField(blank=True, max_length=1024)),
                ('cloth_category', models.CharField(blank=True, max_length=1024)),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_size', models.CharField(blank=True, max_length=10)),
                ('cloth_style', models.CharField(blank=True, max_length=1024)),
                ('cloth_item', models.CharField(blank=True, max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorApply',
        ),
    ]
