# Generated by Django 3.2.20 on 2023-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20230912_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='text',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='text',
            name='sender',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
