# Generated by Django 3.2.20 on 2023-10-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='closet',
            name='image',
            field=models.ImageField(upload_to='C:\\Akshat\\python\\python projects\\internship_stockprogram    stock_trends\network\\static\network\\images'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=8096)),
                ('item_name', models.CharField(max_length=1024)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='C:\\Akshat\\python\\python projects\\internship_stockprogram        stock_trends\network\\static\network\\images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
