# Generated by Django 3.2.20 on 2024-01-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20231003_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='price',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='product_info',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='closet',
            name='image',
            field=models.ImageField(upload_to='network/static/network/images'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='link',
            field=models.CharField(blank=True, max_length=8096),
        ),
    ]
