# Generated by Django 5.0.3 on 2024-03-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20240108_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Closet',
        ),
        migrations.DeleteModel(
            name='Style',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
